before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Z6SJDOJXuxbrna3uZfxFkZSLWInm3fOtaccTiRkOz5zKmkavtzaSCEx+9WhzK3svXnmkrJAweiSDEXph+Mr/l6QEnXGx4FsMuiTEq38eYcmXTBNw6gnnkbPsNBgcgvtnviZjqPqYGwD+U+SvFWa73p6rL0hGBtSsSK7c8az/4HpbPrPmPAJ8yogCa90NXa8PhB/XG9tpLGsOgWWE9/1jvZdo0c8XOU7AMOK6NEZDTsQoMgt21EGPtnb/Y4F/hPuNNTA/g5thELDCjSJXLLQ6G+lQ4HA7QYuVWJ7sGdHyvy2JuIQdMOtsmLUveGb0DTsfhpD6XlQ8Q6zeDVs2i9w3z9LKLdA1ji3wsQtxGOf7szGy3X9d5aR08cqxReri2hSI+XI3mvgqIXs9JyCQWfVzdLkQXPrEXuE3B5ZXOEASIP3SQeKi52LBq3AjwLrL143RcLqYKANIYY5r3hv+ZnjgVVqgqYoOlKfnEIgfj8iP1eRNXgdRMWwwokBh9bmpXq5JS6NpHTpCG7v7WGzAKx80e6cu4JYYWpvqKhNmr1zmMNfEpHd3Q/ruCrTTOEvwUj6ZhzuFCw49aW2k8YhMPs8FnErc36xe3i+F/awD8SxnXx0iyRqIxhCXwnygUNwa5dsJUthsE2NecD+kKdCbmBNTRmzvGlRCovBkLQT+q/QbkOo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
